Additions to Windows, Chromeos and Linux Articles
MiahaCybersec/netrunner.academy pull request #55
Opened 2024-08-27 09:31 UTC by graphene1over

As in my previous PR, I would like to get some feedback. 
I split the significant part from the previous article that was rejected in #54 and added them into their respective Articles.

2024-08-27 17:35 UTC, MiahaCybersec commented on src/content/docs/os-security/linux.md
> +The monolithic nature of the Kernel is a flaw of Linux in itself. While this might fall flat due to a lack of alternatives, but should still be mentioned, as it is a major limitation. Additionaly Lin
Each distribution handles it differently, but a lot of mainstream Linux distributions do have secure boot.

[Ubuntu](https://wiki.ubuntu.com/UEFI/SecureBoot#:~:text=SecureBoot/Testing.-,How%20UEFI%20Secure%20Boot%20works%20on%20Ubuntu,-On%20Ubuntu%2C%20all)
While not as detailed, [Fedora](https://fedoraproject.org/wiki/Secureboot) has support for secure boot as well with a very similar implementation.

Rather than saying "Secureboot at the time of writing is easily bypassed", elaborate by citing sources. Research papers, studies, or academic papers will strengthen this claim and make it easy to fact check. 

Rather than claiming immutable distributions do not achieve their goal, make sure to cite sources. This makes the entire claim easy to fact check and validate.

2024-08-27 17:46 UTC, MiahaCybersec commented on src/content/docs/os-security/linux.md
> +[Secureblue](https://github.com/secureblue/secureblue) has a [couple mitigations](https://github.com/secureblue/secureblue?tab=readme-ov-file#hardening) that are unique to it. The project comes with
Sources for Gnome being the only desktop environment to prevent apps from accessing screen content would be appreciated. 

Otherwise the content of this paragraph looks good. I might request the wording and format to change a bit, but the content itself looks good.

2024-08-27 17:58 UTC, MiahaCybersec commented on src/content/docs/os-security/linux.md
>  [Ubuntu](https://ubuntu.com/download) also has a [list](https://wiki.ubuntu.com/Security/Features) of mitigations they apply, however their effectiveness on a stable distribution is questionable for
> [Ubuntu](https://ubuntu.com/download) also has a [list](https://wiki.ubuntu.com/Security/Features) of mitigations they apply, however their effectiveness on a stable distribution is questionable for reasons described prior.

While stable release distributions do have issues, the mitigations themselves are not questionable. AppArmor and SELinux are used extensively in Android and ChromeOS, arguably some of the most secure operating systems available today. While the memory protections put in place on Ubuntu and Fedora might not be as extensive as `hardened_malloc`, they will mitigate some vulnerabilities. Ubuntu is also one of the few distributions to [make use of Intel's Control-Flow Enforcement Technology](https://wiki.ubuntu.com/Security/Features#kernel-lockdown:~:text=for%20regression%20tests.-,Built%20with%20%2Dfcf%2Dprotection,-Instructs%20the%20compiler) which detects and prevents ROP and JOP. Intel has a [full article](https://www.intel.com/content/www/us/en/developer/articles/technical/technical-look-control-flow-enforcement-technology.html) on this technology for more information.

2024-09-16 06:54 UTC, MiahaCybersec commented
See all open reviews for requested changes. Some polish will be required before this can get merged.

2024-09-20 06:58 UTC, graphene1over commented on src/content/docs/os-security/linux.md
>  [Ubuntu](https://ubuntu.com/download) also has a [list](https://wiki.ubuntu.com/Security/Features) of mitigations they apply, however their effectiveness on a stable distribution is questionable for
fixed

2024-09-22 08:28 UTC, graphene1over commented on src/content/docs/os-security/linux.md
>  [Privsec.dev](https://privsec.dev) has an Article on Linux security and mentions the lack of proper application sandboxing, however, similarly to [madaidan's artice](https://madaidans-insecurities.gi
I am not citing madaidan or privsec as a source, rather criticizing them.

2024-09-22 08:56 UTC, MiahaCybersec requested changes

2024-09-22 09:03 UTC, graphene1over commented on src/content/docs/os-security/linux.md
> +[Ubuntu](https://ubuntu.com/download) also has a [list](https://wiki.ubuntu.com/Security/Features) of mitigations they apply, however their effectiveness on a stable distribution is questionable for
fixed

2024-09-22 09:06 UTC, graphene1over commented on src/content/docs/os-security/linux.md
> +The monolithic nature of the Kernel is a flaw of Linux in itself. While this might fall flat due to a lack of alternatives, but should still be mentioned, as it is a major limitation. Additionaly Lin
fixed

2024-09-22 09:52 UTC, graphene1over commented on src/content/docs/os-security/linux.md
> +The monolithic nature of the Kernel is a flaw of Linux in itself. While this might fall flat due to a lack of alternatives, but should still be mentioned, as it is a major limitation. Additionaly Lin
fixed

2024-09-22 10:00 UTC, graphene1over commented
@MiahaCybersec, requested changes have been implemented.

2024-09-30 08:13 UTC, MiahaCybersec requested changes
One very minor nitpick and then it looks good to merge!

2024-09-30 08:13 UTC, MiahaCybersec commented on src/content/docs/os-security/windows.mdx
> +Windows offers [Smart App Control](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) and [AppLocker](https://learn.microsoft.com/en-us/windows/
```suggestion
Windows offers [Smart App Control](https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003) and [AppLocker](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/applocker/applocker-overview), the latter being cutomizeable and user-configurable over gpedit. Both of these approaches have a common flaw; the Application developers do not comply. Both of the tools rely on the assumption that developers properly sign their applications, which is not the case, even years after the functionality has been provided. Even very large Organizations might not do so properly. This results in either Applications not working, or requires lax permissions like allowing exes from a certain folder to be executed without restrictions, so even a security-minded user cannot fully utilize these tools. Needless to say, this can easily be abused by malware and is similar to how Flatpak sandboxing isn't perfect, which is described in the [Article on Linux](https://github.com/MiahaCybersec/netrunner.academy/blob/main/src/content/docs/os-security/linux.md).
```

2024-09-30 09:07 UTC, MiahaCybersec commented
Looks good to me! Thanks for your contribution! 🥳

2024-09-30 09:07 UTC, merged